api = "0.2"

[buildpack]
id = "org.cloudfoundry.go-compiler"
name = "Go Compiler Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
go = "1.13.*"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "bd26cd4962a362ed3c11835bca32c2e131c2ae050304f2c4df9fa6ded8db85d2"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.12.8.linux-amd64.tar.gz"
version = "1.12.8"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "15c942c1c5193613e813e70ee668e85ad0bd4c26283dd500ee9de1a8ab3c8d12"
source = "https://dl.google.com/go/go1.12.8.src.tar.gz"
source_sha256 = "11ad2e2e31ff63fcf8a2bdffbe9bfa2e1845653358daed593c8c2d03453c9898"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.8.linux-amd64-cflinuxfs3-15c942c1.tar.gz"
version = "1.12.8"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "ac2a6efcc1f5ec8bdc0db0a988bb1d301d64b6d61b7e8d9e42f662fbb75a2b9b"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz"
version = "1.12.9"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "ac2a6efcc1f5ec8bdc0db0a988bb1d301d64b6d61b7e8d9e42f662fbb75a2b9b"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz"
version = "1.12.9"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "14ae7a7109e144cd7f5fddd369b32b8c6fb5bad37c384c13990264931d33263d"
source = "https://dl.google.com/go/go1.12.9.src.tar.gz"
source_sha256 = "ab0e56ed9c4732a653ed22e232652709afbf573e710f56a07f7fdeca578d62fc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.9.linux-amd64-cflinuxfs3-14ae7a71.tar.gz"
version = "1.12.9"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "68a2297eb099d1a76097905a2ce334e3155004ec08cdea85f24527be3c48e856"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.13.linux-amd64.tar.gz"
version = "1.13"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "8b3c3fb89261a596233f7d4c5574fe87c6702f128a01d582243dfa787c0addf3"
source = "https://dl.google.com/go/go1.13.src.tar.gz"
source_sha256 = "3fc0b8b6101d42efd7da1da3029c0a13f22079c0c37ef9730209d8ec665bf122"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.linux-amd64-cflinuxfs3-8b3c3fb8.tar.gz"
version = "1.13"

[[metadata.dependency_deprecation_dates]]
date = 2020-02-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.12.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-09-03T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.13.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["build:git","build:build-essential"]

[[stacks]]
id = "org.cloudfoundry.stacks.tiny"
