
[buildpack]
id = "org.cloudfoundry.buildpacks.go"
name = "Golang Buildpack"
version = "0.0.1"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default_versions]
go = "1.12.4"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "470129e220f48fc1f6001d4dec8007df79be7eaba35d1fe63bca8a6f7762c333"
source = "https://dl.google.com/go/go1.10.7.src.tar.gz"
source_sha256 = "b84a0d7c90789f3a2ec5349dbe7419efb81f1fac9289b6f60df86bd919bd4447"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.10.7.linux-amd64-cflinuxfs3-470129e2.tar.gz"
version = "1.10.7"

[[metadata.dependencies]]
id = "go"
sha256 = "f57bb9f0b1e9c0407393afb4508453f2a1283a89daee99c0d3732e0ba827a889"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.10.8.linux-amd64-cflinuxfs2-f57bb9f0.tar.gz"
version = "1.10.8"

[[metadata.dependencies]]
id = "go"
sha256 = "c80a4f0dc4fa53119bf582aec47ced368ba1f4ca1e0773fc0010097bc9211622"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.10.8.linux-amd64-cflinuxfs3-c80a4f0d.tar.gz"
version = "1.10.8"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "bc6905747d9f063f1775cba7702d0dc48e6932e231e81d04c0e8e2e4139c7f8d"
source = "https://dl.google.com/go/go1.11.7.src.tar.gz"
source_sha256 = "cfbe1078fbb1e34e77ad09de40d96d47ef280ba15791da9f02fc05486a4b16bd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.7.linux-amd64-cflinuxfs3-bc690574.tar.gz"
version = "1.11.7"

[[metadata.dependencies]]
id = "go"
sha256 = "a51895e02d00a7aa72c645a724cd43bf546af40c10df0cb193ff8266b6218ed6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.9.linux-amd64-cflinuxfs2-a51895e0.tar.gz"
version = "1.11.9"

[[metadata.dependencies]]
id = "go"
sha256 = "4217f379920aae70b4086ee987884cd745ab6f0f2c82fdf88a184f77ae6b8c8d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.9.linux-amd64-cflinuxfs3-4217f379.tar.gz"
version = "1.11.9"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "415a638414249badac020ceb5a2faece780be2cc0e7ecda090d2727eb0c78b29"
source = "https://dl.google.com/go/go1.12.2.src.tar.gz"
source_sha256 = "af992580a4a609309c734d46fd4374fe3095961263e609d9b017e2dffc3b7b58"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.2.linux-amd64-cflinuxfs3-415a6384.tar.gz"
version = "1.12.2"

[[metadata.dependencies]]
id = "go"
sha256 = "1a6d80b16a845f6a9692857a5978c0d69a89b58af4d50f66209435beafb07b5b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.4.linux-amd64-cflinuxfs2-1a6d80b1.tar.gz"
version = "1.12.4"

[[metadata.dependencies]]
id = "go"
sha256 = "e68279204493307782c51105c3dd5254ab066d0b5d9aafa3ce3a2878ebbef53f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.4.linux-amd64-cflinuxfs3-e6827920.tar.gz"
version = "1.12.4"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
