api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Go compiler distribution version"
  homepage = "https://github.com/paketo-buildpacks/go-dist"
  id = "paketo-buildpacks/go-dist"
  keywords = ["go", "distribution", "compiler"]
  name = "Paketo Go Distribution Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]
  version = "9.9.9"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go-dist/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.18.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:golang:go:1.18.4:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.18.4?checksum=4525aa6b0e3cecb57845f4060a7075aafc9ab752bb7b6b4cf8a212d43078e1e4&download_url=https://dl.google.com/go/go1.18.4.src.tar.gz"
    sha256 = "3c364727980f71d7714b198f4c6360f9fce99889cef1b1681803ef3a1756356c"
    source = "https://dl.google.com/go/go1.18.4.src.tar.gz"
    source_sha256 = "4525aa6b0e3cecb57845f4060a7075aafc9ab752bb7b6b4cf8a212d43078e1e4"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "io.buildpacks.stacks.jammy", "io.buildpacks.stacks.jammy.tiny"]
    uri = "https://deps.paketo.io/go/go_go1.18.4_linux_x64_bionic_3c364727.tgz"
    version = "1.18.4"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:golang:go:1.18.4:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    stacks = ["*"]
    strip-components = 1
    version = "1.18.4"
    [metadata.dependencies.amd64]
      purl = "pkg:generic/go@go1.19?checksum=c9b099b68d93f5c5c8a8844a89f8db07eaa58270e3a1e01804f17f4cf8df02f5&download_url=https://go.dev/dl/go1.18.4.linux-amd64.tar.gz"
      sha256 = "c9b099b68d93f5c5c8a8844a89f8db07eaa58270e3a1e01804f17f4cf8df02f5"
      source = "https://go.dev/dl/go1.18.4.linux-amd64.tar.gz"
      source_sha256 = "c9b099b68d93f5c5c8a8844a89f8db07eaa58270e3a1e01804f17f4cf8df02f5"
      uri = "https://go.dev/dl/go1.18.4.linux-amd64.tar.gz"
    [metadata.dependencies.arm64]
      purl = "pkg:generic/go@go1.19?checksum=35014d92b50d97da41dade965df7ebeb9a715da600206aa59ce1b2d05527421f&download_url=https://go.dev/dl/go1.18.4.linux-arm64.tar.gz"
      sha256 = "35014d92b50d97da41dade965df7ebeb9a715da600206aa59ce1b2d05527421f"
      source = "https://go.dev/dl/go1.18.4.linux-arm64.tar.gz"
      source_sha256 = "35014d92b50d97da41dade965df7ebeb9a715da600206aa59ce1b2d05527421f"
      uri = "https://go.dev/dl/go1.18.4.linux-arm64.tar.gz"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:golang:go:1.18.5:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.18.5?checksum=9920d3306a1ac536cdd2c796d6cb3c54bc559c226fc3cc39c32f1e0bd7f50d2a&download_url=https://dl.google.com/go/go1.18.5.src.tar.gz"
    sha256 = "f6f0e6be02c4987ea6bc8eb0e960514f2a97bc92ec61cde30b9d9622ed78fb11"
    source = "https://dl.google.com/go/go1.18.5.src.tar.gz"
    source_sha256 = "9920d3306a1ac536cdd2c796d6cb3c54bc559c226fc3cc39c32f1e0bd7f50d2a"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "io.buildpacks.stacks.jammy", "io.buildpacks.stacks.jammy.tiny"]
    uri = "https://deps.paketo.io/go/go_go1.18.5_linux_x64_bionic_f6f0e6be.tgz"
    version = "1.18.5"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:golang:go:1.18.5:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    stacks = ["*"]
    strip-components = 1
    version = "1.18.5"
    [metadata.dependencies.amd64]
      purl = "pkg:generic/go@go1.19?checksum=9e5de37f9c49942c601b191ac5fba404b868bfc21d446d6960acc12283d6e5f2&download_url=https://go.dev/dl/go1.18.5.linux-amd64.tar.gz"
      sha256 = "9e5de37f9c49942c601b191ac5fba404b868bfc21d446d6960acc12283d6e5f2"
      source = "https://go.dev/dl/go1.18.5.linux-amd64.tar.gz"
      source_sha256 = "9e5de37f9c49942c601b191ac5fba404b868bfc21d446d6960acc12283d6e5f2"
      uri = "https://go.dev/dl/go1.18.5.linux-amd64.tar.gz"
    [metadata.dependencies.arm64]
      purl = "pkg:generic/go@go1.19?checksum=006f6622718212363fa1ff004a6ab4d87bbbe772ec5631bab7cac10be346e4f1&download_url=https://go.dev/dl/go1.18.5.linux-arm64.tar.gz"
      sha256 = "006f6622718212363fa1ff004a6ab4d87bbbe772ec5631bab7cac10be346e4f1"
      source = "https://go.dev/dl/go1.18.5.linux-arm64.tar.gz"
      source_sha256 = "006f6622718212363fa1ff004a6ab4d87bbbe772ec5631bab7cac10be346e4f1"
      uri = "https://go.dev/dl/go1.18.5.linux-arm64.tar.gz"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:golang:go:1.19:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.19?checksum=9419cc70dc5a2523f29a77053cafff658ed21ef3561d9b6b020280ebceab28b9&download_url=https://dl.google.com/go/go1.19.src.tar.gz"
    sha256 = "d7363c6f044fa76bc466f8523371b29c085c9fcb7a8ca44875dcc6c234b3b262"
    source = "https://dl.google.com/go/go1.19.src.tar.gz"
    source_sha256 = "9419cc70dc5a2523f29a77053cafff658ed21ef3561d9b6b020280ebceab28b9"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "io.buildpacks.stacks.jammy", "io.buildpacks.stacks.jammy.tiny"]
    uri = "https://deps.paketo.io/go/go_go1.19_linux_x64_bionic_d7363c6f.tgz"
    version = "1.19.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:golang:go:1.19:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    stacks = ["*"]
    strip-components = 1
    version = "1.19.0"
    [metadata.dependencies.amd64]
      purl = "pkg:generic/go@go1.19?checksum=464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6&download_url=https://go.dev/dl/go1.19.linux-amd64.tar.gz"
      sha256 = "464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6"
      source = "https://go.dev/dl/go1.19.linux-amd64.tar.gz"
      source_sha256 = "464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6"
      uri = "https://go.dev/dl/go1.19.linux-amd64.tar.gz"
    [metadata.dependencies.arm64]
      purl = "pkg:generic/go@go1.19?checksum=efa97fac9574fc6ef6c9ff3e3758fb85f1439b046573bf434cccb5e012bd00c8&download_url=https://go.dev/dl/go1.19.linux-arm64.tar.gz"
      sha256 = "efa97fac9574fc6ef6c9ff3e3758fb85f1439b046573bf434cccb5e012bd00c8"
      source = "https://go.dev/dl/go1.19.linux-arm64.tar.gz"
      source_sha256 = "efa97fac9574fc6ef6c9ff3e3758fb85f1439b046573bf434cccb5e012bd00c8"
      uri = "https://go.dev/dl/go1.19.linux-arm64.tar.gz"

  [[metadata.dependency-constraints]]
    constraint = "1.18.*"
    id = "go"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.19.*"
    id = "go"
    patches = 2

[[stacks]]
  id = "*"
