
[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "0.0.4"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
go = "1.12.*"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "2fd47b824d6e32154b0f6c8742d066d816667715763e06cebb710304b195c775"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://dl.google.com/go/go1.11.11.linux-amd64.tar.gz"
version = "1.11.11"

[[metadata.dependencies]]
id = "go"
sha256 = "0bb93e1e55a9b5a65cb2fc5c0f6cd61f63e278a02dc6e9971af1e82dc8c878f9"
source = "https://dl.google.com/go/go1.11.11.src.tar.gz"
source_sha256 = "1fff7c33ef2522e6dfaf6ab96ec4c2a8b76d018aae6fc88ce2bd40f2202d0f8c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.11.linux-amd64-cflinuxfs2-0bb93e1e.tar.gz"
version = "1.11.11"

[[metadata.dependencies]]
id = "go"
sha256 = "969fcee0e6d7b334b39671b59de13ed8069589c213ca766a2ee38e33d822372f"
source = "https://dl.google.com/go/go1.11.11.src.tar.gz"
source_sha256 = "1fff7c33ef2522e6dfaf6ab96ec4c2a8b76d018aae6fc88ce2bd40f2202d0f8c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.11.linux-amd64-cflinuxfs3-969fcee0.tar.gz"
version = "1.11.11"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "e3f92803bae059b5066bed1dc728f160be2f600dc7582b446a1df222f6a976ab"
source = "https://dl.google.com/go/go1.11.12.src.tar.gz"
source_sha256 = "6d7a5ba05476609a7614af3292f29c3be06327503c1f1fdc02ef417870fd6926"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.12.linux-amd64-cflinuxfs2-e3f92803.tar.gz"
version = "1.11.12"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "8843ca9b607f85020f91d2c08fa1e43fcf77a2be8ea2750c043800f0751a74d9"
source = "https://dl.google.com/go/go1.11.12.src.tar.gz"
source_sha256 = "6d7a5ba05476609a7614af3292f29c3be06327503c1f1fdc02ef417870fd6926"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.12.linux-amd64-cflinuxfs3-8843ca9b.tar.gz"
version = "1.11.12"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "7caf172bf643d63d63528d51cb3e530d3198baba1ba25e591a2f2b45eb1d6798"
source = "https://dl.google.com/go/go1.12.5.src.tar.gz"
source_sha256 = "2aa5f088cbb332e73fc3def546800616b38d3bfe6b8713b8a6404060f22503e8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.5.linux-amd64-cflinuxfs3-7caf172b.tar.gz"
version = "1.12.5"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "dbcf71a3c1ea53b8d54ef1b48c85a39a6c9a935d01fc8291ff2b92028e59913c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz"
version = "1.12.6"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "dbcf71a3c1ea53b8d54ef1b48c85a39a6c9a935d01fc8291ff2b92028e59913c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz"
version = "1.12.6"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "f67ab420493b30d0d4f0d36a7526169c93de55ae5cf8ceb73c7647a252fcf0f2"
source = "https://dl.google.com/go/go1.12.6.src.tar.gz"
source_sha256 = "c96c5ccc7455638ae1a8b7498a030fe653731c8391c5f8e79590bce72f92b4ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.6.linux-amd64-cflinuxfs3-f67ab420.tar.gz"
version = "1.12.6"

[[metadata.dependency_deprecation_dates]]
date = 2019-08-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.11.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-02-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.12.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
