
[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "0.0.3"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
go = "1.10.*"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "470129e220f48fc1f6001d4dec8007df79be7eaba35d1fe63bca8a6f7762c333"
source = "https://dl.google.com/go/go1.10.7.src.tar.gz"
source_sha256 = "b84a0d7c90789f3a2ec5349dbe7419efb81f1fac9289b6f60df86bd919bd4447"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.10.7.linux-amd64-cflinuxfs3-470129e2.tar.gz"
version = "1.10.7"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "c80a4f0dc4fa53119bf582aec47ced368ba1f4ca1e0773fc0010097bc9211622"
source = "https://dl.google.com/go/go1.10.8.src.tar.gz"
source_sha256 = "6faf74046b5e24c2c0b46e78571cca4d65e1b89819da1089e53ea57539c63491"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.10.8.linux-amd64-cflinuxfs3-c80a4f0d.tar.gz"
version = "1.10.8"

[[metadata.dependencies]]
id = "go"
sha256 = "d82ad290db8548265283bfe9d8f8485ed2f13599b4256b3b10a9638e025a23de"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.10.linux-amd64-cflinuxfs2-d82ad290.tar.gz"
version = "1.11.10"

[[metadata.dependencies]]
id = "go"
sha256 = "ce35e1a2b3d9c45bd687bb99946fade14572d97793a8788e2436c1cfe860e5fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.10.linux-amd64-cflinuxfs3-ce35e1a2.tar.gz"
version = "1.11.10"

[[metadata.dependencies]]
id = "go"
sha256 = "afedfb53b3fa1519a268c88f01223d08d8e96da8504679c7340e582774b5ac79"
source = "https://dl.google.com/go/go1.11.11.src.tar.gz"
source_sha256 = "1fff7c33ef2522e6dfaf6ab96ec4c2a8b76d018aae6fc88ce2bd40f2202d0f8c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.11.linux-amd64-cflinuxfs2-afedfb53.tar.gz"
version = "1.11.11"

[[metadata.dependencies]]
id = "go"
sha256 = "83a947325bb8837ec3043cbd806ce09e1c6caafbb7508d396650eedbd8616a0a"
source = "https://dl.google.com/go/go1.11.11.src.tar.gz"
source_sha256 = "1fff7c33ef2522e6dfaf6ab96ec4c2a8b76d018aae6fc88ce2bd40f2202d0f8c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.11.linux-amd64-cflinuxfs3-83a94732.tar.gz"
version = "1.11.11"

[[metadata.dependencies]]
id = "go"
sha256 = "904d2357e20b5647bcdcf6b370f9d5a618deffce8bcbfbf4b56fb37f4c97032c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.5.linux-amd64-cflinuxfs2-904d2357.tar.gz"
version = "1.12.5"

[[metadata.dependencies]]
id = "go"
sha256 = "7caf172bf643d63d63528d51cb3e530d3198baba1ba25e591a2f2b45eb1d6798"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.5.linux-amd64-cflinuxfs3-7caf172b.tar.gz"
version = "1.12.5"

[[metadata.dependencies]]
id = "go"
sha256 = "75a8f165c577fec0faedffe98494df795a6a9e5039ab1daeacc00ca04f83fc38"
source = "https://dl.google.com/go/go1.12.6.src.tar.gz"
source_sha256 = "c96c5ccc7455638ae1a8b7498a030fe653731c8391c5f8e79590bce72f92b4ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.6.linux-amd64-cflinuxfs2-75a8f165.tar.gz"
version = "1.12.6"

[[metadata.dependencies]]
id = "go"
sha256 = "888b9bf862b1c553ba0b69b0d25c4d29e04d3f7e24c96d8aff3e3141326d6044"
source = "https://dl.google.com/go/go1.12.6.src.tar.gz"
source_sha256 = "c96c5ccc7455638ae1a8b7498a030fe653731c8391c5f8e79590bce72f92b4ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.6.linux-amd64-cflinuxfs3-888b9bf8.tar.gz"
version = "1.12.6"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
