api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go-compiler"
  name = "Go Compiler Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.13.*"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "4c15009a5f28f9c7b9e5b446ef41a333ad0a303ed4394a355006e43c66599803"
    source = "https://dl.google.com/go/go1.12.15.linux-amd64.tar.gz"
    source_sha256 = "61068419f3d3fcd3cc415c352c4a93d6ae0e723ac18a22ac572b4904d78b5a4c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.12.15-bionic-4c15009a.tgz"
    version = "1.12.15"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "cf1b4415b259b6e7536d67817d490336a60cbc99e159f6697aa5bc6794fa01e8"
    source = "https://dl.google.com/go/go1.12.15.src.tar.gz"
    source_sha256 = "8aba74417e527524ad5724e6e6c21016795d1017692db76d1b0851c6bdec84c3"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.15.linux-amd64-cflinuxfs3-cf1b4415.tgz"
    version = "1.12.15"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "a96cd83b360404c532f85088175fabf53e81854645d8a7fba3a502a507416bda"
    source = "https://dl.google.com/go/go1.12.15.linux-amd64.tar.gz"
    source_sha256 = "61068419f3d3fcd3cc415c352c4a93d6ae0e723ac18a22ac572b4904d78b5a4c"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.12.15-tiny-a96cd83b.tgz"
    version = "1.12.15"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "44877c36371d1e95f1af944fcdf5b7582eaa42929c1b45442451eecf6be9b10b"
    source = "https://dl.google.com/go/go1.12.16.linux-amd64.tar.gz"
    source_sha256 = "bf3a85d75658144c06ce986ba05e07ef08af4320089b74b1d41de3b0f340ea7e"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.12.16-bionic-44877c36.tgz"
    version = "1.12.16"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "87481d7bef97c3db284567763de14c147e67892e507463710269c0265270f3e1"
    source = "https://dl.google.com/go/go1.12.16.src.tar.gz"
    source_sha256 = "ce6e5ed85b4a54ffc01d55a5838ee313acb4a7f109a745440fecbead1d081df8"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.16.linux-amd64-cflinuxfs3-87481d7b.tgz"
    version = "1.12.16"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "ec676b77d4bcceb6290f4b63384d28f9bb0c8db7e15ffbcc43e8164ac52c61ab"
    source = "https://dl.google.com/go/go1.12.16.linux-amd64.tar.gz"
    source_sha256 = "bf3a85d75658144c06ce986ba05e07ef08af4320089b74b1d41de3b0f340ea7e"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.12.16-tiny-ec676b77.tgz"
    version = "1.12.16"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "64f38eac5dea1260fc89c1324e6abe0ccdbd586f91d3e17d189f0f4ed1b74302"
    source = "https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz"
    source_sha256 = "a1bc06deb070155c4f67c579f896a45eeda5a8fa54f35ba233304074c4abbbbd"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.13.6-bionic-64f38eac.tgz"
    version = "1.13.6"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "bd57b335eec881bfeaef4171e53096c3b94ebf1d34cfcf53c87a5afd1a612e63"
    source = "https://dl.google.com/go/go1.13.6.src.tar.gz"
    source_sha256 = "aae5be954bdc40bcf8006eb77e8d8a5dde412722bc8effcdaf9772620d06420c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.6.linux-amd64-cflinuxfs3-bd57b335.tgz"
    version = "1.13.6"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "624ecae3bfa9a8759b68e43902cb6176796c27389150b7c292d75f037603763a"
    source = "https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz"
    source_sha256 = "a1bc06deb070155c4f67c579f896a45eeda5a8fa54f35ba233304074c4abbbbd"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.13.6-tiny-624ecae3.tgz"
    version = "1.13.6"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "5bb47c2673c6c14f4bf2102df35967f88f99825ef0751113457ddaab4ad171b7"
    source = "https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz"
    source_sha256 = "b3dd4bd781a0271b33168e627f7f43886b4c5d1c794a4015abf34e99c6526ca3"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.13.7-bionic-5bb47c26.tgz"
    version = "1.13.7"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "be5201245989826eebf9bff66887786219aebb671dd463f0e2dc911cc483fbc3"
    source = "https://dl.google.com/go/go1.13.7.src.tar.gz"
    source_sha256 = "e4ad42cc5f5c19521fbbbde3680995f2546110b5c6aa2b48c3754ff7af9b41f4"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.7.linux-amd64-cflinuxfs3-be520124.tgz"
    version = "1.13.7"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "97192e9e4f20c7ff04aae845535758aa570203bdf6b5951ed33a6f7a0d2bd0fa"
    source = "https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz"
    source_sha256 = "b3dd4bd781a0271b33168e627f7f43886b4c5d1c794a4015abf34e99c6526ca3"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.13.7-tiny-97192e9e.tgz"
    version = "1.13.7"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-02-01T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.12.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-03T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.13.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.tiny"
