
[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "0.0.4"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
go = "1.12.*"

[[metadata.dependencies]]
id = "go"
sha256 = "d82ad290db8548265283bfe9d8f8485ed2f13599b4256b3b10a9638e025a23de"
source = "https://dl.google.com/go/go1.11.10.src.tar.gz"
source_sha256 = "df27e96a9d1d362c46ecd975f1faa56b8c300f5c529074e9ea79bdd885493c1b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.10.linux-amd64-cflinuxfs2-d82ad290.tar.gz"
version = "1.11.10"

[[metadata.dependencies]]
id = "go"
sha256 = "ce35e1a2b3d9c45bd687bb99946fade14572d97793a8788e2436c1cfe860e5fe"
source = "https://dl.google.com/go/go1.11.10.src.tar.gz"
source_sha256 = "df27e96a9d1d362c46ecd975f1faa56b8c300f5c529074e9ea79bdd885493c1b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.10.linux-amd64-cflinuxfs3-ce35e1a2.tar.gz"
version = "1.11.10"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "0bb93e1e55a9b5a65cb2fc5c0f6cd61f63e278a02dc6e9971af1e82dc8c878f9"
source = "https://dl.google.com/go/go1.11.11.src.tar.gz"
source_sha256 = "1fff7c33ef2522e6dfaf6ab96ec4c2a8b76d018aae6fc88ce2bd40f2202d0f8c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.11.linux-amd64-cflinuxfs2-0bb93e1e.tar.gz"
version = "1.11.11"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "969fcee0e6d7b334b39671b59de13ed8069589c213ca766a2ee38e33d822372f"
source = "https://dl.google.com/go/go1.11.11.src.tar.gz"
source_sha256 = "1fff7c33ef2522e6dfaf6ab96ec4c2a8b76d018aae6fc88ce2bd40f2202d0f8c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.11.linux-amd64-cflinuxfs3-969fcee0.tar.gz"
version = "1.11.11"

[[metadata.dependencies]]
id = "go"
sha256 = "904d2357e20b5647bcdcf6b370f9d5a618deffce8bcbfbf4b56fb37f4c97032c"
source = "https://dl.google.com/go/go1.12.5.src.tar.gz"
source_sha256 = "2aa5f088cbb332e73fc3def546800616b38d3bfe6b8713b8a6404060f22503e8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.5.linux-amd64-cflinuxfs2-904d2357.tar.gz"
version = "1.12.5"

[[metadata.dependencies]]
id = "go"
sha256 = "7caf172bf643d63d63528d51cb3e530d3198baba1ba25e591a2f2b45eb1d6798"
source = "https://dl.google.com/go/go1.12.5.src.tar.gz"
source_sha256 = "2aa5f088cbb332e73fc3def546800616b38d3bfe6b8713b8a6404060f22503e8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.5.linux-amd64-cflinuxfs3-7caf172b.tar.gz"
version = "1.12.5"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "0319ec00e6b1eaaf21862da083f291b484fca175334c00c5a7a0a8ae7299ff3e"
source = "https://dl.google.com/go/go1.12.6.src.tar.gz"
source_sha256 = "c96c5ccc7455638ae1a8b7498a030fe653731c8391c5f8e79590bce72f92b4ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.6.linux-amd64-cflinuxfs2-0319ec00.tar.gz"
version = "1.12.6"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "f67ab420493b30d0d4f0d36a7526169c93de55ae5cf8ceb73c7647a252fcf0f2"
source = "https://dl.google.com/go/go1.12.6.src.tar.gz"
source_sha256 = "c96c5ccc7455638ae1a8b7498a030fe653731c8391c5f8e79590bce72f92b4ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.6.linux-amd64-cflinuxfs3-f67ab420.tar.gz"
version = "1.12.6"

[[metadata.dependency_deprecation_dates]]
date = 2019-08-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.11.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-02-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.12.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
