api = "0.2"

[buildpack]
id = "org.cloudfoundry.go-compiler"
name = "Go Compiler Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
go = "1.13.*"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "aaa84147433aed24e70b31da369bb6ca2859464a45de47c2a5023d8573412f6b"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.12.10.linux-amd64.tar.gz"
version = "1.12.10"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "759cf8459a7a186c04d8821b058a18fa5fd56b3ab4580eedd0c585d6a074bdbd"
source = "https://dl.google.com/go/go1.12.10.src.tar.gz"
source_sha256 = "f56e48fce80646d3c94dcf36d3e3f490f6d541a92070ad409b87b6bbb9da3954"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.10.linux-amd64-cflinuxfs3-759cf845.tar.gz"
version = "1.12.10"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "2c5960292da8b747d83f171a28a04116b2977e809169c344268c893e4cf0a857"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.12.11.linux-amd64.tar.gz"
version = "1.12.11"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "3fff35734538bdbc7f1cef4339114e30033bd1ebe387029ed70ec8f373b76e10"
source = "https://dl.google.com/go/go1.12.11.src.tar.gz"
source_sha256 = "fcf58935236802929f5726e96cd1d900853b377bec2c51b2e37219c658a4950f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.11.linux-amd64-cflinuxfs3-3fff3573.tar.gz"
version = "1.12.11"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "94f874037b82ea5353f4061e543681a0e79657f787437974214629af8407d124"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
version = "1.13.1"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "d74137f4554c8cf04e080d0a27d8fbe47dc221b5c6be314df07d87085cc21abf"
source = "https://dl.google.com/go/go1.13.1.src.tar.gz"
source_sha256 = "81f154e69544b9fa92b1475ff5f11e64270260d46e7e36c34aafc8bc96209358"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.1.linux-amd64-cflinuxfs3-d74137f4.tar.gz"
version = "1.13.1"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "293b41a6ccd735eebcfb4094b6931bfd187595555cecf3e4386e9e119220c0b7"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://dl.google.com/go/go1.13.2.linux-amd64.tar.gz"
version = "1.13.2"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "6a2c8366b8b0ef4ec3df6b0c0a0e58a466a7af4136252398920c88d889a13843"
source = "https://dl.google.com/go/go1.13.2.src.tar.gz"
source_sha256 = "1ea68e01472e4276526902b8817abd65cf84ed921977266f0c11968d5e915f44"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.2.linux-amd64-cflinuxfs3-6a2c8366.tar.gz"
version = "1.13.2"

[[metadata.dependency_deprecation_dates]]
date = 2020-02-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.12.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-09-03T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.13.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["build:git","build:build-essential"]

[[stacks]]
id = "org.cloudfoundry.stacks.tiny"
