api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go-compiler"
  name = "Go Compiler Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.13.*"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "da036454cb3353f9f507f0ceed4048feac611065e4e1818b434365eb32ac9bdc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://dl.google.com/go/go1.12.13.linux-amd64.tar.gz"
    version = "1.12.13"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "e218849aaf190cfdada98d3e36662eab64c60914bf6d7ba8e520be040f673191"
    source = "https://dl.google.com/go/go1.12.13.src.tar.gz"
    source_sha256 = "5383d3b8db4baa48284ffcb14606d9cad6f03e9db843fa6d835b94d63cccf5a7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.13.linux-amd64-cflinuxfs3-e218849a.tar.gz"
    version = "1.12.13"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "925a1a9d8b31c2425d7313fe73d3342288968a66e26cd8bf1b6b5656f4603fcb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://dl.google.com/go/go1.12.14.linux-amd64.tar.gz"
    version = "1.12.14"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "b940bc1bb309a7b381e3345315cbe0e48fb31f38afe12195c54ef37245f9a8df"
    source = "https://dl.google.com/go/go1.12.14.src.tar.gz"
    source_sha256 = "39dbf05f7e2ffcb19b08f07d53dcc96feadeb1987fef9e279e7ff0c598213064"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.14.linux-amd64-cflinuxfs3-b940bc1b.tar.gz"
    version = "1.12.14"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "692d17071736f74be04a72a06dab9cac1cd759377bd85316e52b2227604c004c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz"
    version = "1.13.4"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "d7e7ae00be94366b567808802e51b7cc879ec0efe3d29b0e6d2a1fe97350cd7b"
    source = "https://dl.google.com/go/go1.13.4.src.tar.gz"
    source_sha256 = "95dbeab442ee2746b9acf0934c8e2fc26414a0565c008631b04addb8c02e7624"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.4.linux-amd64-cflinuxfs3-d7e7ae00.tar.gz"
    version = "1.13.4"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "512103d7ad296467814a6e3f635631bd35574cab3369a97a323c9a585ccaa569"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz"
    version = "1.13.5"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "fedef14df0fc373546067501db2009d31516bfe9217045028b4cf8fd06afc9df"
    source = "https://dl.google.com/go/go1.13.5.src.tar.gz"
    source_sha256 = "27d356e2a0b30d9983b60a788cf225da5f914066b37a6b4f69d457ba55a626ff"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.5.linux-amd64-cflinuxfs3-fedef14d.tar.gz"
    version = "1.13.5"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-02-01T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.12.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-03T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.13.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.tiny"
