
[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "0.0.3"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default-version]
go = "1.10.*"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "470129e220f48fc1f6001d4dec8007df79be7eaba35d1fe63bca8a6f7762c333"
source = "https://dl.google.com/go/go1.10.7.src.tar.gz"
source_sha256 = "b84a0d7c90789f3a2ec5349dbe7419efb81f1fac9289b6f60df86bd919bd4447"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.10.7.linux-amd64-cflinuxfs3-470129e2.tar.gz"
version = "1.10.7"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "c80a4f0dc4fa53119bf582aec47ced368ba1f4ca1e0773fc0010097bc9211622"
source = "https://dl.google.com/go/go1.10.8.src.tar.gz"
source_sha256 = "6faf74046b5e24c2c0b46e78571cca4d65e1b89819da1089e53ea57539c63491"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.10.8.linux-amd64-cflinuxfs3-c80a4f0d.tar.gz"
version = "1.10.8"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "4217f379920aae70b4086ee987884cd745ab6f0f2c82fdf88a184f77ae6b8c8d"
source = "https://dl.google.com/go/go1.11.9.src.tar.gz"
source_sha256 = "ee80684b352f8d6b49d804d4e615f015ae92da41c4096cfee89ed4783b2498e3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.9.linux-amd64-cflinuxfs3-4217f379.tar.gz"
version = "1.11.9"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "ce35e1a2b3d9c45bd687bb99946fade14572d97793a8788e2436c1cfe860e5fe"
source = "https://dl.google.com/go/go1.11.10.src.tar.gz"
source_sha256 = "df27e96a9d1d362c46ecd975f1faa56b8c300f5c529074e9ea79bdd885493c1b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.10.linux-amd64-cflinuxfs3-ce35e1a2.tar.gz"
version = "1.11.10"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "e68279204493307782c51105c3dd5254ab066d0b5d9aafa3ce3a2878ebbef53f"
source = "https://dl.google.com/go/go1.12.4.src.tar.gz"
source_sha256 = "4affc3e610cd8182c47abbc5b0c0e4e3c6a2b945b55aaa2ba952964ad9df1467"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.4.linux-amd64-cflinuxfs3-e6827920.tar.gz"
version = "1.12.4"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "7caf172bf643d63d63528d51cb3e530d3198baba1ba25e591a2f2b45eb1d6798"
source = "https://dl.google.com/go/go1.12.5.src.tar.gz"
source_sha256 = "2aa5f088cbb332e73fc3def546800616b38d3bfe6b8713b8a6404060f22503e8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.5.linux-amd64-cflinuxfs3-7caf172b.tar.gz"
version = "1.12.5"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
