
[buildpack]
id = "org.cloudfoundry.go-compiler"
name = "Go Compiler Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
go = "1.12.*"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "14ec881815eb9e6618f95df5eb385d961283efc196d97912595ba6484a56180d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://dl.google.com/go/go1.11.12.linux-amd64.tar.gz"
version = "1.11.12"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "8843ca9b607f85020f91d2c08fa1e43fcf77a2be8ea2750c043800f0751a74d9"
source = "https://dl.google.com/go/go1.11.12.src.tar.gz"
source_sha256 = "6d7a5ba05476609a7614af3292f29c3be06327503c1f1fdc02ef417870fd6926"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.12.linux-amd64-cflinuxfs3-8843ca9b.tar.gz"
version = "1.11.12"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "50fe8e13592f8cf22304b9c4adfc11849a2c3d281b1d7e09c924ae24874c6daa"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://dl.google.com/go/go1.11.13.linux-amd64.tar.gz"
version = "1.11.13"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "a2e08a5f55d207071966d97ae94615677c654c1699d6c61378e64b6c1318b79a"
source = "https://dl.google.com/go/go1.11.13.src.tar.gz"
source_sha256 = "5032095fd3f641cafcce164f551e5ae873785ce7b07ca7c143aecd18f7ba4076"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.11.13.linux-amd64-cflinuxfs3-a2e08a5f.tar.gz"
version = "1.11.13"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "66d83bfb5a9ede000e33c6579a91a29e6b101829ad41fffb5c5bb6c900e109d9"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz"
version = "1.12.7"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "040d6b6f34a246e08468d32fa47fd5f5088aea72ed9dd441c9c5b4922b596cc9"
source = "https://dl.google.com/go/go1.12.7.src.tar.gz"
source_sha256 = "95e8447d6f04b8d6a62de1726defbb20ab203208ee167ed15f83d7978ce43b13"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.7.linux-amd64-cflinuxfs3-040d6b6f.tar.gz"
version = "1.12.7"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "bd26cd4962a362ed3c11835bca32c2e131c2ae050304f2c4df9fa6ded8db85d2"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://dl.google.com/go/go1.12.8.linux-amd64.tar.gz"
version = "1.12.8"

[[metadata.dependencies]]
id = "go"
name = "Go"
sha256 = "15c942c1c5193613e813e70ee668e85ad0bd4c26283dd500ee9de1a8ab3c8d12"
source = "https://dl.google.com/go/go1.12.8.src.tar.gz"
source_sha256 = "11ad2e2e31ff63fcf8a2bdffbe9bfa2e1845653358daed593c8c2d03453c9898"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.8.linux-amd64-cflinuxfs3-15c942c1.tar.gz"
version = "1.12.8"

[[metadata.dependency_deprecation_dates]]
date = 2019-08-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.11.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-02-01T00:00:00Z
link = "https://golang.org/doc/devel/release.html"
name = "go"
version_line = "1.12.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["build:git","build:build-essential"]
